train:
  test_size: 0.2
  random_state: 42

models:
  random_forest:
    n_estimators: 100
    random_state: 42
  
  logistic_regression:
    max_iter: 200
    random_state: 42

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
