name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint code
        run: |
          flake8 src --max-line-length=120

      - name: Run tests
        run: |
          echo "No test suite yet, add pytest here"

  build-push:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/iris-api:latest -f docker/Dockerfile .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/iris-api:latest
