name: CI - Iris Classification FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 8000:8000
          - 9090:9090
          - 3000:3000

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Build and run containers
      run: |
        docker-compose up --build -d
        sleep 20  # wait for services to start
        
    - name: Wait for FastAPI to start
      run: sleep 15

    - name: Test FastAPI /metrics
      run: |
        curl --fail http://localhost:8000/metrics

    - name: Tear down
      if: always()
      run: docker-compose down

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}